[package]
name = "bark"
version = "0.1.0"
edition = "2018"

[profile.release]
lto = true

[dependencies]
rocket = "0.5.0-rc.1"
lettre = { version = "0.10.0-rc.3", features = ["tokio1", "tokio1-native-tls"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1"
