[package]
name = "meow"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.3"
lazy_static = "1"
actix-web = "4.0.0-beta.5"
rusoto_core = { version = "0.46.0", default_features = false, features = [ "rustls" ] }
rusoto_s3 =  { version = "0.46.0", default_features = false, features = [ "rustls" ] }
futures = "0.3.14"
tokio = "1"
tokio-stream = "0.1.5"
anyhow = "1"
url = "2"
