[package]
name = "meow"
version = "0.1.0"
edition = "2018"

[profile.release]
lto = true

[dependencies]
rand = "0.8"
actix-web = "4.1"
actix-files = "0.6"
tokio = { version = "1", features = [ "fs" ] }
anyhow = "1"
url = "2"
argh = "0.1"
lazy_static = "1.4"
